project:
  type: website
  output-dir: docs

website:
  title: "SFA"
  navbar:
    left:
      - href: pages/instructions.qmd
        text: Instructions
      - href: pages/datasets.qmd
        text: Datasets
      - href: pages/pca.qmd
        text: PCA -- Turkey
      - href: pages/csvd.qmd
        text: CSVD
      - href: pages/spca.qmd
        text: Sparse PCA -- Beers
      - href: pages/sca.qmd
        text: Sparse CA -- TV
      - href: pages/splsc.qmd
        text: Sparse PLSC -- Wines
      - href: pages/about.qmd
        text: About us
      - icon: github
        href: https://github.com/vguillemot/sensometrics2024_SFA

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



