---
title: "Sparse Factor Analysis"
subtitle: "Monday June 3, at 9:00 - 12:00"
---

Instructors:

  - Vincent Guillemot (Institut Pasteur, France)
  - Vincent Le Goff (CNRGH, Evry, France)
  - Ju-Chi Yu (CAMH, Toronto, Canada)
  - Hervé Abdi (UTD, Dallas, USA)

This is the companion website of the Sensometrics 2024 tutorial on sparse factor analysis.

This tutorial is designed for sensory and consumer scientists who want to improve their data analysis skills using component-based methods in R. The focus of this training session is to teach participants how to navigate through complex and noisy multivariate sensory datasets to extract relevant observations, assessors, properties, and variables. The main objective is to provide attendees with the expertise to carry out a range of sparse multivariate analyses in R, including sparse PCA, CA, and MCA.

During the course, attendees will work with specific packages created for sparse multivariate analysis (such as SPAFAC). They will be provided with datasets containing both quantitative and qualitative variables to apply sparse MCA, CA, and PCA methods. This hands-on approach will help them determine the optimal degree of sparsity and accurately interpret their findings. All the course materials, including an extensive R script, are open-source and will be available for use after the completion of the tutorial.

This three-hour session is particularly beneficial for sensory and consumer scientists looking to enhance their data visualization skills using R/Rstudio. Participants should have a basic understanding of R/RStudio, including data types, variables, functions, and package management. A fundamental grasp of statistical concepts will also be helpful. Participants must bring a laptop with R and Rstudio pre-installed. 

More instructions [here](pages/instructions.qmd).

## Detailed (proposed) schedule

```{r schedule, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
knitr::kable(
  readxl::read_excel("data/schedule.xlsx") %>%
    mutate(across(1:3, ~ format(.x, format = "%H:%M"))))
```

## Shared code

This a link to the shared code that we will use during the tutorial: [Shared code](https://docs.google.com/document/d/1r6d6LNm5QZmlMsBdban5cMtH43wHc6k5KKmvIZLJxG8/edit?usp=sharing)

## Datasets

The datasets that we will use during the tutorial are detailed [on this page](pages/datasets.qmd). You can download the datasets with the links below, or the links on the dataset page, or the links at the beginning of each "part" of the tutorial:

  * [Beers](../data/beers.xlsx): Ten tasters rated the intensity of twelve descriptors for six beers,
  * [Turkey products](../data/turkey.xlsx): A trained sensory panel of 8 rated 8 turkey breast products from Mexico on 12 attributes using a 10-point Likert scale
  * [TV and salad](../data/salad_and_tv.xlsx): Data from the INCA 3 study include responses from over 5,800 people on dietary habits, focusing on "hours spent watching TV" and "salad consumption."
  * [Wines](../data/wines.xlsx): 36 wines from Argentina, Canada, and the USA, along with a mystery French wine, are evaluated on descriptors, price, chemistry, and sensory properties, organized into four data blocks.


## References

 * Abdi, H., Gomez, C., & Delmas, M. (2022). Méthodes Statistiques Multivariées pour l'Analyse Sensorielle et les Etudes Consommateurs.
 * Abdi, H., Eslami, A., & Guillemot, V. (2018). Canonical correlation analysis (CCA). In R. Alhajj and J. Rokne (Eds.), Encyclopedia of Social Networks and Mining (2nd Edition). New York: Springer Verlag.
  * Abdi, H., & Williams, L.J. (2013). Partial least squares methods: Partial least squares correlation and partial least square regression. In: B. Reisfeld & A. Mayeno (Eds.), Methods in Molecular Biology: Computational Toxicology. New York: Springer Verlag. pp. 549-579.
 * Carine Dubuisson, Ariane Dufour, Sandrine Carrillo, Peggy Drouillet-Pinard, Sabrina Havard, Jean-Luc Volatier (2019). The Third French Individual and National Food Consumption (INCA3) Survey 2014-2015: method, design and participation rate in the framework of a European harmonization process. Public Health Nutrition: 22(4), 584–600. doi:10.1017/S1368980018002896.







